export const LOGIN = "LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const SUCCESS_GET_CATEGORIES = "SUCCESS_GET_CATEGORIES";
export const FAILED_GET_CATEGORIES = "FAILED_GET_CATEGORIES";

export const GET_BLOGS = "GET_BLOGS";
export const SUCCESS_GET_BLOGS = "SUCCESS_GET_BLOGS";
export const FAILED_GET_BLOGS = "FAILED_GET_BLOGS";

export const GET_BLOGS_BY_CATEGORY = "GET_BLOGS_BY_CATEGORY";
export const SUCCESS_GET_BLOGS_BY_CATEGORY = "SUCCESS_GET_BLOGS_BY_CATEGORY";
export const FAILED_GET_BLOGS_BY_CATEGORY = "FAILED_GET_BLOGS_BY_CATEGORY";

export const GET_BLOGS_BY_USER = "GET_BLOGS_BY_USER";
export const SUCCESS_GET_BLOGS_BY_USER = "SUCCESS_GET_BLOGS_BY_USER";
export const FAILED_GET_BLOGS_BY_USER = "FAILED_GET_BLOGS_BY_USER";

export const DELETE_BLOGS = "DELETE_BLOGS";
export const SUCCESS_DELETE_BLOGS = "SUCCESS_DELETE_BLOGS";
export const FAILED_DELETE_BLOGS = "FAILED_DELETE_BLOGS";

export const GET_BLOG = "GET_BLOG";
export const SUCCESS_GET_BLOG = "SUCCESS_GET_BLOG";
export const FAILED_GET_BLOG = "FAILED_GET_BLOG";

export const GET_COMMENTS = "GET_COMMENTS";
export const SUCCESS_GET_COMMENTS = "SUCCESS_GET_COMMENTS";
export const FAILED_GET_COMMENTS = "FAILED_GET_COMMENTS";

export const ADD_COMMENT = "ADD_COMMENT";
export const SUCCESS_ADD_COMMENT = "SUCCESS_ADD_COMMENT";
export const FAILED_ADD_COMMENT = "FAILED_ADD_COMMENT";


